### ISSUE TITLE
When loading new items on an empty list ocreader is crashing

### ISSUE THREAD

**Issue by Lakrimar** [schaal/ocreader#100]
## Description of the issue
When opening the app and refreshing it to load new issues the app crashes when the list was empty before. When reopening the app the new items are listed correctly.

## Expected behavior
OCReader should display new items instead of crashing...

## Steps to reproduce

1. Open OCReader
2. Recognize an empty list
3. Refresh to load new items (swipe from top to bottom)

## Your Environment

* OCReader version: 0.47
* Nextcloud news version: 14.1.11
* Android version: LOS 16 (Android 9)

### Logcat

```
06-10 11:31:39.047 23306 23818 D API     : Sync started: email.schaal.ocreader.action.FULL_SYNC
06-10 11:31:41.584 23306 23818 D API     : Sync finished: email.schaal.ocreader.action.FULL_SYNC
06-10 11:31:41.627 23306 23306 D AndroidRuntime: Shutting down VM
06-10 11:31:41.635 23306 23306 E AndroidRuntime: FATAL EXCEPTION: main
06-10 11:31:41.635 23306 23306 E AndroidRuntime: Process: email.schaal.ocreader, PID: 23306
06-10 11:31:41.635 23306 23306 E AndroidRuntime: java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at io.realm.BaseRealm.checkIfValid(BaseRealm.java:4)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at io.realm.BaseRealm.beginTransaction(BaseRealm.java:1)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at io.realm.Realm.executeTransaction(Realm.java:1)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at email.schaal.ocreader.database.FeedViewModel.updateTemporaryFeed(FeedViewModel.kt:5)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at email.schaal.ocreader.ListActivity.access$updateSyncStatus(ListActivity.kt:1)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at email.schaal.ocreader.ListActivity$onCreate$3.onSharedPreferenceChanged(ListActivity.kt:9)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:607)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at android.app.SharedPreferencesImpl$EditorImpl.lambda$notifyListeners$0(SharedPreferencesImpl.java:613)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at android.app.-$$Lambda$SharedPreferencesImpl$EditorImpl$3CAjkhzA131V3V-sLfP2uy0FWZ0.run(Unknown Source:4)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
06-10 11:31:41.635 23306 23306 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
06-10 11:31:41.647   566   971 W ActivityManager:   Force finishing activity email.schaal.ocreader/.ListActivity
06-10 11:31:41.671 23306 23306 I Process : Sending signal. PID: 23306 SIG: 9
```

**Comment by lazerleif** [comment]
Same thing for me

Oneplus 6, with LineageOS 16
OCreader v. 0.52 from fdroid
