### ISSUE TITLE
Illegal Argument: This field(id) is not nullable.

### ISSUE THREAD

**Issue by s3lph** [schaal/ocreader#113]
## Description of the issue
After upgrading from 0.53 to 0.54, and refreshing the news, the app enters a crash loop.

The issue persists when clearing the app's cache.

## Expected behavior
News should be refreshed successfully, no crash should occur.

## Steps to reproduce

1. Install OCReader 0.54 from F-Droid
2. Open OCReader
3. Refresh news

## Your Environment

* OCReader version: 0.54
* Nextcloud news version: 15.1.0
* Android version: 10

### Logcat

```
12-14 22:21:31.660 30307 30307 E AndroidRuntime: FATAL EXCEPTION: main
12-14 22:21:31.660 30307 30307 E AndroidRuntime: Process: email.schaal.ocreader, PID: 30307
12-14 22:21:31.660 30307 30307 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{email.schaal.ocreader/email.schaal.ocreader.ListActivity}: java.lang.IllegalArgumentException: Illegal Argument: This field(id) is not nullable.
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Illegal Argument: This field(id) is not nullable.
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at io.realm.internal.TableQuery.nativeIsNull(Native Method)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at io.realm.internal.TableQuery.isNull(TableQuery.java:1)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at io.realm.RealmQuery.equalTo(RealmQuery.java:14)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at email.schaal.ocreader.database.model.Folder.getAll(Folder.kt:23)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at email.schaal.ocreader.database.FeedViewModel.<init>(FeedViewModel.kt:16)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at email.schaal.ocreader.database.FeedViewModel$FeedViewModelFactory.create(FeedViewModel.kt:1)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:15)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at email.schaal.ocreader.ListActivity.getFeedViewModel(Unknown Source:2)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at email.schaal.ocreader.ListActivity.onCreate(ListActivity.kt:21)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7824)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7813)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
12-14 22:21:31.660 30307 30307 E AndroidRuntime: 	... 11 more
```

**Comment by s3lph** [comment]
Ok, clearing the app's storage makes the issue disappear, after logging into Nextcloud again, news can be fetched. The crash however reappears when enabling the "show only unread articles" option.
