### ISSUE TITLE
Timeout Exception

### ISSUE THREAD

**Issue by cwmke** [schaal/ocreader#44]
## Description of the issue
When starting ocreader for the first time, the loading symbol shows followed by an error similar to `````java.net timeout exception:timeout`````. Some articles load but only a fraction. 

## Expected behavior
All articles load on first startup. 

## Steps to reproduce
1. Start app for first time and login. 
2. Wait while it loads articles. 
3. Timeout error. 

## Your Environment

* OCReader version: .28
* Nextcloud news version: 10.1.0
* Android version: 7.1.1

### Logcat

```
03-27 17:20:18.028  7264  7264 W email.schaal.ocreader.database.Queries: Database will be reset
6426 03-27 17:20:18.063  7264  7264 D email.schaal.ocreader.service.SyncService: email.schaal.ocreader.action.SYNC_STARTED: email.schaal.ocreader.action.FULL_SYNC
03-27 17:20:18.388  7264  7264 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-27 17:20:18.406  7264  7264 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-27 17:20:18.407  7264  7264 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-27 17:20:18.407  7264  7264 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-27 17:20:38.670  7264  7264 D email.schaal.ocreader.service.SyncService: email.schaal.ocreader.action.SYNC_FINISHED: email.schaal.ocreader.action.FULL_SYNC
03-27 17:20:44.355  7264  7956 I email.schaal.ocreader.util.IcoRequestHandler: .ico decoding failed, trying again using BitmapFactory: null
03-27 17:21:11.752  7264  7264 D email.schaal.ocreader.service.SyncService: email.schaal.ocreader.action.SYNC_STARTED: email.schaal.ocreader.action.FULL_SYNC

03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: stacktrace
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: timeout
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at email.schaal.ocreader.api.APIv12$3$1.run(APIv12.java:365)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at java.lang.Thread.run(Thread.java:761)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: Caused by: java.net.SocketTimeoutException: timeout
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okio.Okio$4.newTimeoutException(Okio.java:227)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okio.AsyncTimeout.exit(AsyncTimeout.java:274)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:67)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at email.schaal.ocreader.http.HttpManager$AuthorizationInterceptor.intercept(HttpManager.java:91)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at okhttp3.RealCall.execute(RealCall.java:63)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at email.schaal.ocreader.api.APIv12$UpdatedItemsCallable.getResponse(APIv12.java:483)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at email.schaal.ocreader.api.APIv12$RealmCallable.call(APIv12.java:424)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at email.schaal.ocreader.api.APIv12$RealmCallable.call(APIv12.java:412)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-27 17:22:12.209  7264  7899 E email.schaal.ocreader.api.APIv12: 	... 3 more
03-27 17:22:12.261  7264  7264 D email.schaal.ocreader.service.SyncService: email.schaal.ocreader.action.SYNC_FINISHED: email.schaal.ocreader.action.FULL_SYNC

```

**Comment by schaal** [comment]
Can't say for sure without a logcat, but this sounds like a connectivity issue.

**Comment by schaal** [comment]
Probably a server issue, please comment if you think otherwise (best with a logcat)

**Comment by cwmke** [comment]
Sorry about the delay getting this to you. The logcat is now included. From my previous use, I believe the issue may have something to do with having more than 10,000 articles. I'm not positive that's the exact number but the issue happened after having around 12,000-14,000 unread articles.
