### ISSUE TITLE
UpdatedDate Exception

### ISSUE THREAD

**Issue by tobiasKaminsky** [schaal/ocreader#56]
## Description of the issue
```
Caused by: com.squareup.moshi.JsonDataException: Expected a long but was NULL at path $.items[15].updatedDate
                                                                         at com.squareup.moshi.JsonUtf8Reader.nextLong(JsonUtf8Reader.java:756)
                                                                         at email.schaal.ocreader.api.json.ItemTypeAdapter.fromJson(ItemTypeAdapter.java:150)
                                                                         at email.schaal.ocreader.api.json.ItemTypeAdapter.fromJson(ItemTypeAdapter.java:44)
                                                                         at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:75)
                                                                         at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:52)
                                                                         at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127)
                                                                         at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:204)
                                                                         at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:166)
                                                                         at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127)```
```

If you need more, I am happy to help/debug you.

## Expected behavior
show new articles

## Steps to reproduce

1. update app via fdroid
2. update server app
3. refresh articles in app

## Your Environment

* OCReader version: latest fdroid app
* Nextcloud news version: latest server app
* Android version: 7.x

### Logcat
(Read http://www.makeuseof.com/tag/get-logcat-reporting-bugs-android/ if you are not sure how to get the logcat output.)

```
Please paste the relevant logcat output here
```

**Comment by lauhayden** [comment]
I'm running into this exact bug. It only showed up once I updated to the newest Nextcloud News app (10.2.0). Clearing cache and data, then re-entering login info results in another bug (possibly related), filed here [ will edit].

Android: 7.1.2
OCReader: 0.26
Nextcloud: 11.0.2
Nextcloud News: 10.2.0

**Comment by schaal** [comment]
A fixed version is already released, should be available from FDroid soon.

**Comment by lauhayden** [comment]
Hm, Fdroid still hasn't built 0.33... this is slightly annoying.

**Comment by tobiasKaminsky** [comment]
Yeah...Fdoid sometimes seems to have hiccups.
I have fetched the apk from https://github.com/schaal/ocreader/releases and installed it manually.

**Comment by schaal** [comment]
Fixed version now available on FDroid
