### ISSUE TITLE
Login loop on OCReader 0.45

### ISSUE THREAD

**Issue by melkor0** [schaal/ocreader#95]
## Description of the issue
Upon attempting to allow access of OCReader to Nextcloud, OCReader throws me back to prompt to enter a server address. OCReader does not proceed further than giving access to the Nextcloud-account; tapping on grant access ("Zugriff gewähren ->") leads to the first register prompt.
In Nextcloud I can see that OCReader has access to the Nextcloud filesystem (in NC: click avatar -> Settings -> Security -> Devices & Sessions ("Geräte und Sitzungen")).
The webserver logs don't show irregularities and the Nextcloud app can get access through the same login procedure as OCReader's.

## Expected behavior
OCReader complete the login process and grant me access to the account's Nextcloud news feed

## Steps to reproduce

1. Install OCReader (tested w/ apk from this github repo and F-Droids versions)
2. Upon opening app fill in server address and tap continue (with or without trailing / - doesn't matter).
3. On the Nextcloud promtpt tap login ("Anmelden ->")
4. Enter username and password and tap on login ("Anmelden ->")
5.  On the Account access prompt  ("Kontozugriff") tap on Allow access ("Zugriff gewähren ->")
6. Back on step 2.

## Your Environment

* OCReader version: 0.45
* Nextcloud news version: 18.0.4
* Android version: 10

### Logcat

```
05-27 16:46:04.552 W/System.err(17695): java.lang.IllegalArgumentException: baseUrl must end in /: https://mydomain.xxxxxxxx.eu/nextcloud
05-27 16:46:04.553 W/System.err(17695): 	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:5)
05-27 16:46:04.553 W/System.err(17695): 	at email.schaal.ocreader.api.API$Companion.login(API.kt:10)
05-27 16:46:04.553 W/System.err(17695): 	at email.schaal.ocreader.LoginFlowActivity$onCreate$1$1.invokeSuspend(LoginFlowActivity.kt:5)
05-27 16:46:04.553 W/System.err(17695): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
05-27 16:46:04.553 W/System.err(17695): 	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:18)
05-27 16:46:04.553 W/System.err(17695): 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:15)
05-27 16:46:04.553 W/System.err(17695): 	at androidx.activity.ActivityResultLauncherKt.launch$default(ActivityResultLauncher.kt:7)
05-27 16:46:04.553 W/System.err(17695): 	at email.schaal.ocreader.LoginFlowActivity$onCreate$1.onChanged(LoginFlowActivity.kt:5)
05-27 16:46:04.553 W/System.err(17695): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
05-27 16:46:04.553 W/System.err(17695): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
05-27 16:46:04.553 W/System.err(17695): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:4)
05-27 16:46:04.553 W/System.err(17695): 	at email.schaal.ocreader.ui.loginflow.LoginFlowWebViewFragment$onCreateView$2.shouldOverrideUrlLoading(LoginFlowWebViewFragment.kt:20)
05-27 16:46:04.553 W/System.err(17695): 	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:16)
05-27 16:46:04.553 W/System.err(17695): 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-27 16:46:04.553 W/System.err(17695): 	at android.os.MessageQueue.next(MessageQueue.java:336)
05-27 16:46:04.553 W/System.err(17695): 	at android.os.Looper.loop(Looper.java:174)
05-27 16:46:04.553 W/System.err(17695): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-27 16:46:04.553 W/System.err(17695): 	at java.lang.reflect.Method.invoke(Native Method)
05-27 16:46:04.553 W/System.err(17695): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-27 16:46:04.553 W/System.err(17695): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
05-27 16:46:04.585 W/email.schaal.ocreader.database.Queries(17695): Database will be reset
05-27 16:46:04.588 W/REALM_JNI(17695): Primary key value already exists: 0 .
05-27 16:46:04.588 W/REALM_JNI(17695): (/Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp:197)
05-27 16:46:04.589 W/System.err(17695): io.realm.exceptions.RealmPrimaryKeyConstraintException: Primary key value already exists: 0 .
05-27 16:46:04.589 W/System.err(17695): (/Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp:197)
05-27 16:46:04.589 W/System.err(17695): 	at io.realm.internal.OsObject.nativeCreateNewObjectWithLongPrimaryKey(Native Method)
05-27 16:46:04.589 W/System.err(17695): 	at io.realm.internal.OsObject.createWithPrimaryKey(OsObject.java:16)
05-27 16:46:04.589 W/System.err(17695): 	at io.realm.Realm.createObject(Realm.java:6)
05-27 16:46:04.589 W/System.err(17695): 	at email.schaal.ocreader.database.Queries$initialData$1.execute(Queries.kt:22)
05-27 16:46:04.589 W/System.err(17695): 	at io.realm.Realm.executeTransaction(Realm.java:2)
05-27 16:46:04.589 W/System.err(17695): 	at email.schaal.ocreader.database.Queries.resetDatabase(Queries.kt:3)
05-27 16:46:04.589 W/System.err(17695): 	at email.schaal.ocreader.ListActivity$getLoginResult$2.onActivityResult(ListActivity.kt:4)
05-27 16:46:04.589 W/System.err(17695): 	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:5)
05-27 16:46:04.589 W/System.err(17695): 	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:1)
05-27 16:46:04.589 W/System.err(17695): 	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:9)
05-27 16:46:04.589 W/System.err(17695): 	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
05-27 16:46:04.589 W/System.err(17695): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
05-27 16:46:04.589 W/System.err(17695): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
05-27 16:46:04.589 W/System.err(17695): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
05-27 16:46:04.589 W/System.err(17695): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-27 16:46:04.590 W/System.err(17695): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-27 16:46:04.590 W/System.err(17695): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
05-27 16:46:04.590 W/System.err(17695): 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-27 16:46:04.590 W/System.err(17695): 	at android.os.Looper.loop(Looper.java:214)
05-27 16:46:04.590 W/System.err(17695): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-27 16:46:04.590 W/System.err(17695): 	at java.lang.reflect.Method.invoke(Native Method)
05-27 16:46:04.590 W/System.err(17695): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-27 16:46:04.590 W/System.err(17695): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
05-27 16:46:04.612 I/ActivityTaskManager(  923): START u0 {cmp=email.schaal.ocreader/.LoginFlowActivity} from uid 10263
05-27 16:46:04.614 D/QCOM PowerHAL(  674): LAUNCH HINT: ON
05-27 16:46:04.617 D/QCOM PowerHAL(  674): Activity launch hint handled
05-27 16:46:04.663 W/ActivityThread(17695): handleWindowVisibility: no activity for token android.os.BinderProxy@2e3026
05-27 16:46:04.667 W/System.err(17695): java.lang.IllegalStateException
05-27 16:46:04.667 W/System.err(17695): 	at email.schaal.ocreader.api.API.<init>(API.kt:9)
05-27 16:46:04.668 W/System.err(17695): 	at email.schaal.ocreader.service.SyncJobIntentService$onHandleWork$1.invokeSuspend(SyncJobIntentService.kt:5)
05-27 16:46:04.668 W/System.err(17695): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
05-27 16:46:04.668 W/System.err(17695): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
05-27 16:46:04.668 W/System.err(17695): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
05-27 16:46:04.668 W/System.err(17695): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:12)

```

**Comment by schaal** [comment]
Thanks for the detailed report, I will release a new version with the fix shortly.
